// import SelectLocalidades from "../components/forms/selectLocalidades";

let rut = "781094706";
const id = Math.random(10,200).toString(36)
const date = '1988-12-22';

const campos3 = [
  { campo: "shippingAddress.Calle", type: "street", detalle: "Calle de Envío", valua: "El Gato Campestre" },
  { campo: "shippingAddress.Numero", type: "text", detalle: "Numero de Envío", valua: "15487" },
  { campo: "shippingAddress.Casa_o_depto", type: "text", detalle: "Casa o depto de Envío", valua: "1100" },
  {
    campo: "shippingAddress.Código_Postal",
    type: "text",
    detalle: "Código Postal de Envío",
    valua: "120123"
  },
  { campo: "shipping.Tipo_de_Despacho", type: "text", detalle: "Tipo de Despacho", valua: "Envío Región FedEx", options: ["Envío Gratis Santiago","Envío Fedex Regiones", "Retira en Local", "Envío Santiago Pago"] },
  { campo: "shipping.Fecha_de_Despacho_o_Retiro", type: "date", detalle: "Fecha de Retiro o Despacho", valua: `${date}` },
  { campo: "shipping.Nombre_Retira", type: "text", detalle: "Nombre de Retira", valua: "Carlos Espinoza" },
  { campo: "shipping.Rut_Retira", type: "text", detalle: "Rut de Retira", valua: "15020576k" },
  { campo: "shipping.Observación", type: "text", detalle: "Observación", valua: "Dejar en la el local azúl de en frente, Preguntar por Yolanda" },
];

//tipo de despacho
//fecha de despacho o retiro
// datos de retira rut nombre patente
//crear campo flete en negocio
//observacion

const campos2 = [
  // {
  //   campo: "billing.Tipo_de_DTE",
  //   type: "text",
  //   detalle: "Ingresa el tipo DTE",
  //   valua: "Factura",
  // },
  {
    campo: "billing.Razón_Social",
    type: "text",
    detalle: "Ingresa la Razón Social * ",
    valua: "INDUSTRIAS DE ALIMENTOS TRENDY S.A.",
  },
  {
    campo: "billing.Rut_Empresa",
    type: "text",
    detalle: "Ingresa tu Rut de Empresa * ",
    valua: "781094706",
  },
  {
    campo: "billing.Giro",
    type: "text",
    detalle: "Ingresa tu Giro * ",
    valua: "HELADOS",
  },
];
const campos1 = [
  // { campo: "contact.user", type: "text", detalle: "Id del Usuario", valua: `${0}` },
  { campo: "contact.DealId", type: "text", detalle: "Id del Negocio * ", valua: `${id}` },
  { campo: "contact.Rut", type: "text", detalle: "Rut del cliente", valua: `${rut}` },
  {
    campo: "contact.Nombre",
    type: "text",
    detalle: "Nombre del cliente",
    valua: "Juan Ramon",
  },
  {
    campo: "contact.Apellido",
    type: "text",
    detalle: "Apellido del cliente",
    valua: "Perez Carvajal",
  },
  {
    campo: "contact.Email",
    type: "email",
    detalle: "Email del cliente * ",
    valua: "elloropablo@gmail.com",
  },
  {
    campo: "contact.Telefono",
    type: "phone",
    detalle: "Telefono del cliente",
    valua: "56987654321",
  },
  {
    component: "",
  }
];
const dirFac1 = [
  {
    campo: "billingAddress.Calle",
    type: "street",
    detalle: "Calle de Facturación * ",
    valua: "LO ZANARTU",
  },
  {
    campo: "billingAddress.Número",
    type: "text",
    detalle: "Número de Dirección Facturación * ",
    valua: "11",
  },
  {
    campo: "billingAddress.Departamento",
    type: "text",
    detalle: "Casa o depto de Facturación",
    valua: "777",
  },
  {
    campo: "billingAddress.Código_Postal",
    type: "text",
    detalle: "Código Postal de Facturación",
    valua: "750123",
  },
];
const dirEnv1 = [
  { campo: "shippingAddress.Calle", type: "street", detalle: "Calle de Envío", valua: "Calle Manuel Rodriguez" },
  { campo: "shippingAddress.Numero", type: "text", detalle: "Numero de Envío", valua: "15487" },
  { campo: "shippingAddress.Casa_o_depto", type: "text", detalle: "Casa o depto de Envío", valua: "1100" },
  { campo: "shippingAddress.Comuna", type: "town", detalle: "Comuna de Envío", valua: "Antofagasta" },
  { campo: "shippingAddress.Región", type: "state", detalle: "Región de Envío", valua: "Antofagasta" },
  { campo: "shippingAddress.Ciudad", type: "city", detalle: "Ciudad de Envío", valua: "Antofagasta" },
  {
    campo: "shippingAddress.Código_Postal",
    type: "text",
    detalle: "Código Postal de Envío",
    valua: "120123"
  },
];
const products1 = [
  // { campo: "products.SKU", type: "text", detalle: "SKU * ", valua: "100021" },
  // { campo: "products.Nombre_Producto", type: "text", detalle: "Nombre", valua: "LAVAPLATOS 2 TAZAS SECADOR VENELP-160SD" },
  // { campo: "products.Precio", type: "text", detalle: "Precio * ", valua: "150000" },
  { campo: "products.Cantidad", type: "text", detalle: "Cantidad * ", valua: "5" },
  { campo: "products.Descuento", type: "text", detalle: "Descuento", valua: "1" },
];
const pago1 = [
  {
    campo: "payment.Metodo_de_Pago",
    type: "text",
    detalle: "Metodo de Pago",
  valua: ["C","3","6","M"],
  options: [ "Pago a 0 - 30 - 60", "Transferencia", "WebPay", "Mercado Pago"]
  },
  {
    campo: "payment.Tipo_de_Pago",
    type: "text",
    detalle: "Tipo de Pago",
  valua: ["P000","P015","P030","P060","P090"],
  options: [ "Pago al contado sin DPP", "Crédito a 15 días", "Crédito a 30 días", "Crédito a 60 días", "Crédito a 90 días"]
  },
  {
    campo: "payment.orden_de_compra",
    type: "text",
    detalle: "Orden de Compra",
  valua: "76667"
  },
  {
    campo: "payment.centro",
    type: "text",
    detalle: "Centro",
  valua: ["1100","1200"],
  options: [ "Lautaro", "Panamericana"]
  },
  {
    campo: "payment.almacen",
    type: "text",
    detalle: "Almacén",
  valua: ["1014","1208","1209","1015"],
  options: [ "Lautaro Distribución Venta Directa", "Panamericana 08", "Panamericana 09", "Lautaro Ecommerce"]
  },
  {
    campo: "payment.canal",
    type: "text",
    detalle: "Canal",
  valua: ["24","28","18","27", "23"],
  options: [ "Venta Directa", "Distribución", "Ecommerce", "Grandes Cuentas", "Imega"]
  },
  {
    campo: "payment.clase_de_pedido",
    type: "text",
    detalle: "Clase de Pedido",
  valua: ["ZVDI","ZDIS", "ZECF", "ZECB", "ZVFA","ZPGD"],
  options: [ "Venta Directa", "Distribución", "Ecommerce Factura","Ecommerce Boleta", "Facturación Anticipada", "Guía de Despacho"]
  },
  /**agrega campos para estos titulos
   * 
   */
];

//regiones
const regiones = [
  { id: 1, nombre: 'Arica y Parinacota' },
  { id: 2, nombre: 'Tarapacá' },
  { id: 3, nombre: 'Antofagasta' },
  { id: 4, nombre: 'Atacama' },
  { id: 5, nombre: 'Coquimbo' },
  { id: 6, nombre: 'Valparaíso' },
  { id: 7, nombre: 'Libertador General Bernardo O\'Higgins' },
  { id: 8, nombre: 'Maule' },
  { id: 9, nombre: 'Biobío' },
  { id: 10, nombre: 'La Araucanía' },
  { id: 11, nombre: 'Los Ríos' },
  { id: 12, nombre: 'Los Lagos' },
  { id: 13, nombre: 'Metropolitana de Santiago' },
  { id: 14, nombre: 'Aysén del General Carlos Ibáñez del Campo' },
  { id: 15, nombre: 'Magallanes y de la Antártica Chilena' },
];

//capitales regionales 
const ciudades = [
  { id: 1, nombre: 'Arica', region: 1 },
  { id: 2, nombre: 'Iquique', region: 2 },
  { id: 3, nombre: 'Antofagasta', region: 3 },
  { id: 4, nombre: 'Copiapó', region: 4 },
  { id: 5, nombre: 'La Serena', region: 5 },
  { id: 6, nombre: 'Valparaíso', region: 6 },
  { id: 7, nombre: 'Rancagua', region: 7 },
  { id: 8, nombre: 'Talca', region: 8 },
  { id: 9, nombre: 'Concepción', region: 9 },
  { id: 10, nombre: 'Temuco', region: 10 },
  { id: 11, nombre: 'Valdivia', region: 11 },
  { id: 12, nombre: 'Puerto Montt', region: 12 },
  { id: 13, nombre: 'Santiago', region: 13 },
  { id: 14, nombre: 'Coyhaique', region: 14 },
  { id: 15, nombre: 'Punta Arenas', region: 15 },
];

//comunas
const comunas = [
  { id: 1, nombre: 'Arica', region: 1 },
  { id: 2, nombre: 'Camarones', region: 1 },
  { id: 3, nombre: 'Putre', region: 1 },
  { id: 4, nombre: 'General Lagos', region: 2 },
  { id: 5, nombre: 'Iquique', region: 2 },
  { id: 6, nombre: 'Alto Hospicio', region: 2 },
  { id: 7, nombre: 'Camiña', region: 2 },
  { id: 8, nombre: 'Colchane', region: 2 },
  { id: 9, nombre: 'Huara', region: 2 },
  { id: 10, nombre: 'Pica', region: 2 },
  { id: 11, nombre: 'Pozo Almonte', region: 2 },
  { id: 12, nombre: 'Antofagasta', region: 3 },
  { id: 13, nombre: 'Mejillones', region: 3 },
  { id: 14, nombre: 'Sierra Gorda', region: 3 },
  { id: 15, nombre: 'Taltal', region: 3 },
  { id: 16, nombre: 'Calama', region: 3 },
  { id: 17, nombre: 'Ollagüe', region: 3 },
  { id: 18, nombre: 'San Pedro de Atacama', region: 3 },
  { id: 19, nombre: 'María Elena', region: 3 },
  { id: 20, nombre: 'Tocopilla', region: 3 },
  { id: 21, nombre: 'Chañaral', region: 4 },
  { id: 22, nombre: 'Diego de Almagro', region: 4 },
  { id: 23, nombre: 'Caldera', region: 4 },
  { id: 24, nombre: 'Copiapó', region: 4 },
  { id: 25, nombre: 'Tierra Amarilla', region: 4 },
  { id: 26, nombre: 'Alto del Carmen', region: 4 },
  { id: 27, nombre: 'Freirina', region: 4 },
  { id: 28, nombre: 'Huasco', region: 4 },
  { id: 29, nombre: 'Vallenar', region: 4 },
  { id: 30, nombre: 'Andacollo', region: 5 },
  { id: 31, nombre: 'Canela', region: 5 },
  { id: 32, nombre: 'Combarbalá', region: 5 },
  { id: 33, nombre: 'Coquimbo', region: 5 },
  { id: 34, nombre: 'Illapel', region: 5 },
  { id: 35, nombre: 'La Higuera', region: 5 },
  { id: 36, nombre: 'La Serena', region: 5 },
  { id: 37, nombre: 'Los Vilos', region: 5 },
  { id: 38, nombre: 'Monte Patria', region: 5 },
  { id: 39, nombre: 'Ovalle', region: 5 },
  { id: 40, nombre: 'Paiguano', region: 5 },
  { id: 41, nombre: 'Punitaqui', region: 5 },
  { id: 42, nombre: 'Río Hurtado', region: 5 },
  { id: 43, nombre: 'Salamanca', region: 5 },
  { id: 44, nombre: 'Vicuña', region: 5 },
  { id: 45, nombre: 'Algarrobo', region: 6 },
  { id: 46, nombre: 'Cabildo', region: 6 },
  { id: 47, nombre: 'Calle Larga', region: 6 },
  { id: 48, nombre: 'Cartagena', region: 6 },
  { id: 49, nombre: 'Casablanca', region: 6 },
  { id: 50, nombre: 'Catemu', region: 6 },
  { id: 51, nombre: 'Concón', region: 6 },
  { id: 52, nombre: 'El Quisco', region: 6 },
  { id: 53, nombre: 'El Tabo', region: 6 },
  { id: 54, nombre: 'Hijuelas', region: 6 },
  { id: 55, nombre: 'Isla de Pascua', region: 6 },
  { id: 56, nombre: 'Juan Fernández', region: 6 },
  { id: 57, nombre: 'La Cruz', region: 6 },
  { id: 58, nombre: 'La Ligua', region: 6 },
  { id: 59, nombre: 'Limache', region: 6 },
  { id: 60, nombre: 'Llaillay', region: 6 },
  { id: 61, nombre: 'Los Andes', region: 6 },
  { id: 62, nombre: 'Nogales', region: 6 },
  { id: 63, nombre: 'Olmué', region: 6 },
  { id: 64, nombre: 'Panquehue', region: 6 },
  { id: 65, nombre: 'Papudo', region: 6 },
  { id: 66, nombre: 'Petorca', region: 6 },
  { id: 67, nombre: 'Puchuncaví', region: 6 },
  { id: 68, nombre: 'Putaendo', region: 6 },
  { id: 69, nombre: 'Quillota', region: 6 },
  { id: 70, nombre: 'Quilpué', region: 6 },
  { id: 71, nombre: 'Quintero', region: 6 },
  { id: 72, nombre: 'Rinconada', region: 6 },
  { id: 73, nombre: 'San Antonio', region: 6 },
  { id: 74, nombre: 'San Esteban', region: 6 },
  { id: 75, nombre: 'San Felipe', region: 6 },
  { id: 76, nombre: 'Santa María', region: 6 },
  { id: 77, nombre: 'Santo Domingo', region: 6 },
  { id: 78, nombre: 'Valparaíso', region: 6 },
  { id: 79, nombre: 'Villa Alemana', region: 6 },
  { id: 80, nombre: 'Viña del Mar', region: 6 },
  { id: 81, nombre: 'Zapallar', region: 6 },
  { id: 82, nombre: 'Chépica', region: 7 },
  { id: 83, nombre: 'Chimbarongo', region: 7 },
  { id: 84, nombre: 'Codegua', region: 7 },
  { id: 85, nombre: 'Coinco', region: 7 },
  { id: 86, nombre: 'Coltauco', region: 7 },
  { id: 87, nombre: 'Doñihue', region: 7 },
  { id: 88, nombre: 'Graneros', region: 7 },
  { id: 89, nombre: 'La Estrella', region: 7 },
  { id: 90, nombre: 'Las Cabras', region: 7 },
  { id: 91, nombre: 'Litueche', region: 7 },
  { id: 92, nombre: 'Lolol', region: 7 },
  { id: 93, nombre: 'Machalí', region: 7 },
  { id: 94, nombre: 'Malloa', region: 7 },
  { id: 95, nombre: 'Marchihue', region: 7 },
  { id: 96, nombre: 'Mostazal', region: 7 },
  { id: 97, nombre: 'Nancagua', region: 7 },
  { id: 98, nombre: 'Navidad', region: 7 },
  { id: 99, nombre: 'Olivar', region: 7 },
  { id: 100, nombre: 'Palmilla', region: 7 },
  { id: 101, nombre: 'Paredones', region: 7 },
  { id: 102, nombre: 'Peralillo', region: 7 },
  { id: 103, nombre: 'Peumo', region: 7 },
  { id: 104, nombre: 'Pichidegua', region: 7 },
  { id: 105, nombre: 'Pichilemu', region: 7 },
  { id: 106, nombre: 'Placilla', region: 7 },
  { id: 107, nombre: 'Pumanque', region: 7 },
  { id: 108, nombre: 'Quinta de Tilcoco', region: 7 },
  { id: 109, nombre: 'Rancagua', region: 7 },
  { id: 110, nombre: 'Rengo', region: 7 },
  { id: 111, nombre: 'Requínoa', region: 7 },
  { id: 112, nombre: 'San Fernando', region: 7 },
  { id: 113, nombre: 'San Vicente', region: 7 },
  { id: 114, nombre: 'Santa Cruz', region: 7 },
  { id: 115, nombre: 'Cauquenes', region: 8 },
  { id: 116, nombre: 'Chanco', region: 8 },
  { id: 117, nombre: 'Colbún', region: 8 },
  { id: 118, nombre: 'Constitución', region: 8 },
  { id: 119, nombre: 'Curepto', region: 8 },
  { id: 120, nombre: 'Curicó', region: 8 },
  { id: 121, nombre: 'Empedrado', region: 8 },
  { id: 122, nombre: 'Hualañé', region: 8 },
  { id: 123, nombre: 'Licantén', region: 8 },
  { id: 124, nombre: 'Linares', region: 8 },
  { id: 125, nombre: 'Longaví', region: 8 },
  { id: 126, nombre: 'Maule', region: 8 },
  { id: 127, nombre: 'Molina', region: 8 },
  { id: 128, nombre: 'Parral', region: 8 },
  { id: 129, nombre: 'Pelarco', region: 8 },
  { id: 130, nombre: 'Pelluhue', region: 8 },
  { id: 131, nombre: 'Pencahue', region: 8 },
  { id: 132, nombre: 'Rauco', region: 8 },
  { id: 133, nombre: 'Retiro', region: 8 },
  { id: 134, nombre: 'Romeral', region: 8 },
  { id: 135, nombre: 'Río Claro', region: 8 },
  { id: 136, nombre: 'Sagrada Familia', region: 8 },
  { id: 137, nombre: 'San Clemente', region: 8 },
  { id: 138, nombre: 'San Javier', region: 8 },
  { id: 139, nombre: 'San Rafael', region: 8 },
  { id: 140, nombre: 'Talca', region: 8 },
  { id: 141, nombre: 'Teno', region: 8 },
  { id: 142, nombre: 'Vichuquén', region: 8 },
  { id: 143, nombre: 'Villa Alegre', region: 8 },
  { id: 144, nombre: 'Yerbas Buenas', region: 8 },
  { id: 145, nombre: 'Alto Biobío', region: 9 },
  { id: 146, nombre: 'Antuco', region: 9 },
  { id: 147, nombre: 'Arauco', region: 9 },
  { id: 148, nombre: 'Cabrero', region: 9 },
  { id: 149, nombre: 'Cañete', region: 9 },
  { id: 150, nombre: 'Chiguayante', region: 9 },
  { id: 151, nombre: 'Concepción', region: 9 },
  { id: 152, nombre: 'Contulmo', region: 9 },
  { id: 153, nombre: 'Coronel', region: 9 },
  { id: 154, nombre: 'Curanilahue', region: 9 },
  { id: 155, nombre: 'Florida', region: 9 },
  { id: 156, nombre: 'Hualqui', region: 9 },
  { id: 157, nombre: 'Laja', region: 9 },
  { id: 158, nombre: 'Lebu', region: 9 },
  { id: 159, nombre: 'Los Álamos', region: 9 },
  { id: 160, nombre: 'Los Ángeles', region: 9 },
  { id: 161, nombre: 'Lota', region: 9 },
  { id: 162, nombre: 'Mulchén', region: 9 },
  { id: 163, nombre: 'Nacimiento', region: 9 },
  { id: 164, nombre: 'Negrete', region: 9 },
  { id: 165, nombre: 'Penco', region: 9 },
  { id: 166, nombre: 'Quilaco', region: 9 },
  { id: 167, nombre: 'Quilleco', region: 9 },
  { id: 168, nombre: 'San Pedro de la Paz', region: 9 },
  { id: 169, nombre: 'San Rosendo', region: 9 },
  { id: 170, nombre: 'Santa Bárbara', region: 9 },
  { id: 171, nombre: 'Santa Juana', region: 9 },
  { id: 172, nombre: 'Talcahuano', region: 9 },
  { id: 173, nombre: 'Tirúa', region: 9 },
  { id: 174, nombre: 'Tomé', region: 9 },
  { id: 175, nombre: 'Tucapel', region: 9 },
  { id: 176, nombre: 'Yumbel', region: 9 },
  { id: 177, nombre: 'Alto del Carmen', region: 10 },
  { id: 178, nombre: 'Angol', region: 10 },
  { id: 179, nombre: 'Carahue', region: 10 },
  { id: 180, nombre: 'Cholchol', region: 10 },
  { id: 181, nombre: 'Collipulli', region: 10 },
  { id: 182, nombre: 'Cunco', region: 10 },
  { id: 183, nombre: 'Curacautín', region: 10 },
  { id: 184, nombre: 'Curarrehue', region: 10 },
  { id: 185, nombre: 'Ercilla', region: 10 },
  { id: 186, nombre: 'Freire', region: 10 },
  { id: 187, nombre: 'Galvarino', region: 10 },
  { id: 188, nombre: 'Gorbea', region: 10 },
  { id: 189, nombre: 'Lautaro', region: 10 },
  { id: 190, nombre: 'Loncoche', region: 10 },
  { id: 191, nombre: 'Lonquimay', region: 10 },
  { id: 192, nombre: 'Los Sauces', region: 10 },
  { id: 193, nombre: 'Lumaco', region: 10 },
  { id: 194, nombre: 'Melipeuco', region: 10 },
  { id: 195, nombre: 'Nueva Imperial', region: 10 },
  { id: 196, nombre: 'Padre Las Casas', region: 10 },
  { id: 197, nombre: 'Perquenco', region: 10 },
  { id: 198, nombre: 'Pitrufquén', region: 10 },
  { id: 199, nombre: 'Pucón', region: 10 },
  { id: 200, nombre: 'Purén', region: 10 },
  { id: 201, nombre: 'Renaico', region: 10 },
  { id: 202, nombre: 'Saavedra', region: 10 },
  { id: 203, nombre: 'Temuco', region: 10 },
  { id: 204, nombre: 'Teodoro Schmidt', region: 10 },
  { id: 205, nombre: 'Toltén', region: 10 },
  { id: 206, nombre: 'Traiguén', region: 10 },
  { id: 207, nombre: 'Victoria', region: 10 },
  { id: 208, nombre: 'Vilcún', region: 10 },
  { id: 209, nombre: 'Villarrica', region: 10 },
  { id: 210, nombre: 'Corral', region: 11 },
  { id: 211, nombre: 'Futrono', region: 11 },
  { id: 212, nombre: 'La Unión', region: 11 },
  { id: 213, nombre: 'Lago Ranco', region: 11 },
  { id: 214, nombre: 'Lanco', region: 11 },
  { id: 215, nombre: 'Los Lagos', region: 11 },
  { id: 216, nombre: 'Máfil', region: 11 },
  { id: 217, nombre: 'Mariquina', region: 11 },
  { id: 218, nombre: 'Paillaco', region: 11 },
  { id: 219, nombre: 'Panguipulli', region: 11 },
  { id: 220, nombre: 'Valdivia', region: 11 },
  { id: 221, nombre: 'Ancud', region: 12 },
  { id: 222, nombre: 'Calbuco', region: 12 },
  { id: 223, nombre: 'Castro', region: 12 },
  { id: 224, nombre: 'Chaitén', region: 12 },
  { id: 225, nombre: 'Chonchi', region: 12 },
  { id: 226, nombre: 'Cochamó', region: 12 },
  { id: 227, nombre: 'Curaco de Vélez', region: 12 },
  { id: 228, nombre: 'Dalcahue', region: 12 },
  { id: 229, nombre: 'Fresia', region: 12 },
  { id: 230, nombre: 'Frutillar', region: 12 },
  { id: 231, nombre: 'Futaleufú', region: 12 },
  { id: 232, nombre: 'Hualaihué', region: 12 },
  { id: 233, nombre: 'Llanquihue', region: 12 },
  { id: 234, nombre: 'Los Muermos', region: 12 },
  { id: 235, nombre: 'Maullín', region: 12 },
  { id: 236, nombre: 'Osorno', region: 12 },
  { id: 237, nombre: 'Palena', region: 12 },
  { id: 238, nombre: 'Puerto Montt', region: 12 },
  { id: 239, nombre: 'Puerto Octay', region: 12 },
  { id: 240, nombre: 'Puerto Varas', region: 12 },
  { id: 241, nombre: 'Puqueldón', region: 12 },
  { id: 242, nombre: 'Purranque', region: 12 },
  { id: 243, nombre: 'Puyehue', region: 12 },
  { id: 244, nombre: 'Queilén', region: 12 },
  { id: 245, nombre: 'Quellón', region: 12 },
  { id: 246, nombre: 'Quemchi', region: 12 },
  { id: 247, nombre: 'Quinchao', region: 12 },
  { id: 248, nombre: 'Puerto Aysén', region: 14 },
  { id: 249, nombre: 'Cisnes', region: 14 },
  { id: 250, nombre: 'Guaitecas', region: 14 },
  { id: 251, nombre: 'Cochrane', region: 14 },
  { id: 252, nombre: 'O\'Higgins', region: 14 },
  { id: 253, nombre: 'Tortel', region: 14 },
  { id: 254, nombre: 'Chile Chico', region: 14 },
  { id: 255, nombre: 'Río Ibáñez', region: 14 },
  { id: 256, nombre: 'Punta Arenas', region: 15 },
  { id: 257, nombre: 'Laguna Blanca', region: 15 },
  { id: 258, nombre: 'Río Verde', region: 15 },
  { id: 259, nombre: 'San Gregorio', region: 15 },
  { id: 260, nombre: 'Porvenir', region: 15 },
  { id: 261, nombre: 'Primavera', region: 15 },
  { id: 262, nombre: 'Timaukel', region: 15 },
  { id: 263, nombre: 'Natales', region: 15 },
  { id: 264, nombre: 'Torres del Paine', region: 15 },
  { id: 265, nombre: 'Antártica', region: 15 },
  { id: 266, nombre: 'Cabo de Hornos', region: 15 },
  { id: 268, nombre: 'Cerrillos', region: 13 },
  { id: 269, nombre: 'Cerro Navia', region: 13 },
  { id: 270, nombre: 'Conchalí', region: 13 },
  { id: 271, nombre: 'El Bosque', region: 13 },
  { id: 272, nombre: 'Estación Central', region: 13 },
  { id: 273, nombre: 'Huechuraba', region: 13 },
  { id: 274, nombre: 'Independencia', region: 13 },
  { id: 275, nombre: 'La Cisterna', region: 13 },
  { id: 276, nombre: 'La Florida', region: 13 },
  { id: 277, nombre: 'La Granja', region: 13 },
  { id: 278, nombre: 'La Pintana', region: 13 },
  { id: 279, nombre: 'La Reina', region: 13 },
  { id: 280, nombre: 'Las Condes', region: 13 },
  { id: 281, nombre: 'Lo Barnechea', region: 13 },
  { id: 282, nombre: 'Lo Espejo', region: 13 },
  { id: 283, nombre: 'Lo Prado', region: 13 },
  { id: 284, nombre: 'Macul', region: 13 },
  { id: 285, nombre: 'Maipú', region: 13 },
  { id: 286, nombre: 'Ñuñoa', region: 13 },
  { id: 287, nombre: 'Pedro Aguirre Cerda', region: 13 },
  { id: 288, nombre: 'Peñalolén', region: 13 },
  { id: 289, nombre: 'Providencia', region: 13 },
  { id: 290, nombre: 'Pudahuel', region: 13 },
  { id: 291, nombre: 'Quilicura', region: 13 },
  { id: 292, nombre: 'Quinta Normal', region: 13 },
  { id: 293, nombre: 'Recoleta', region: 13 },
  { id: 294, nombre: 'Renca', region: 13 },
  { id: 295, nombre: 'San Joaquín', region: 13 },
  { id: 296, nombre: 'San Miguel', region: 13 },
  { id: 297, nombre: 'San Ramón', region: 13 },
  { id: 298, nombre: 'Santiago', region: 13 },
  { id: 299, nombre: 'Vitacura', region: 13 },
  { id: 300, nombre: 'El Monte', region: 13 },
  { id: 301, nombre: 'Isla de Maipo', region: 13 },
  { id: 302, nombre: 'Padre Hurtado', region: 13 },
  { id: 303, nombre: 'Peñaflor', region: 13 },
  { id: 304, nombre: 'Talagante', region: 13 }]

const Datas = [campos1, dirFac1, dirEnv1, products1, pago1, campos2, campos3, regiones, comunas, ciudades];

export default { Datas };
