// //regiones
// const regiones = [
//     { id: 1, nombre: 'Arica y Parinacota' },
//     { id: 2, nombre: 'Tarapacá' },
//     { id: 3, nombre: 'Antofagasta' },
//     { id: 4, nombre: 'Atacama' },
//     { id: 5, nombre: 'Coquimbo' },
//     { id: 6, nombre: 'Valparaíso' },
//     { id: 13, nombre: 'Metropolitana de Santiago' },
//     { id: 7, nombre: 'Libertador General Bernardo O\'Higgins' },
//     { id: 8, nombre: 'Maule' },
//     { id: 9, nombre: 'Biobío' },
//     { id: 10, nombre: 'La Araucanía' },
//     { id: 11, nombre: 'Los Ríos' },
//     { id: 12, nombre: 'Los Lagos' },
//     { id: 14, nombre: 'Aysén del General Carlos Ibáñez del Campo' },
//     { id: 15, nombre: 'Magallanes y de la Antártica Chilena' },
// ];

// //capitales regionales 

// Arica; Iquique; Antofagasta; Copiapó; La Serena; Valparaíso; Rancagua; Talca; Concepción; Temuco; 
// Valdivia; 
// Puerto Montt; 
// Santiago; 
// Coyhaique; 
// Punta Arenas; 


// //comunas

// Arica;
// Camarones;
// utre;
// General Lagos;
// Iquique;
// Alto Hospicio;
// Camiña;
// Colchane;
// Huara;
// Pica;
// Pozo Almonte;
// Antofagasta;
// Mejillones;
// Sierra Gorda;
// Taltal;
// Calama;
// Ollagüe;
// San Pedro de Atacama;
// María Elena;
// Tocopilla;
// Chañaral;
// Diego de Almagro;
// Caldera;
// Copiapó;
// Tierra Amarilla;
// Alto del Carmen;
// Freirina;
// Huasco;
// Vallenar;
// Andacollo;
// Canela;
// Combarbalá;
// Coquimbo;
// Illapel;
// La Higuera;
// La Serena;
// Los Vilos;
// Monte Patria;
// Ovalle;
// Paiguano;
// Punitaqui;
// Río Hurtado;
// Salamanca;
// Vicuña;
// Algarrobo;
// Cabildo;
// Calle Larga;
// Cartagena;
// Casablanca;
// Catemu;
// Concón;
// El Quisco;
// El Tabo;
// Hijuelas;
// Isla de Pascua;
// Juan Fernández;
// La Cruz;
// La Ligua;
// Limache;
// Llaillay;
// Los Andes;
// Nogales;
// Olmué;
// Panquehue;
// Papudo;
// Petorca;
// Puchuncaví;
// Putaendo;
// Quillota;
// Quilpué;
// Quintero;
// Rinconada;
// San Antonio;
// San Esteban;
// San Felipe;
// Santa María;
// Santo Domingo;
// Valparaíso;
// Villa Alemana;
// Viña del Mar;
// Zapallar;
// Chépica;
// Chimbarongo;
// Codegua;
// Coinco;
// Coltauco;
// Doñihue;
// Graneros;
// La Estrella;
// Las Cabras;
// Litueche;
// Lolol;
// Machalí;
// Malloa;
// Marchihue;
// Mostazal;
// Nancagua;
// Navidad;
// Olivar;
// Palmilla;
// Paredones;
// Peralillo;
// Peumo;
// Pichidegua;
// Pichilemu;
// Placilla;
// Pumanque;
// Quinta de Tilcoco;
// Rancagua;
// Rengo;
// Requínoa;
// San Fernando;
// San Vicente;
// Santa Cruz;
// Cauquenes;
// Chanco;
// Colbún;
// Constitución;
// Curepto;
// Curicó;
// Empedrado;
// Hualañé;
// Licantén;
// Linares;
// Longaví;
// Maule;
// Molina;
// Parral;
// Pelarco;
// Pelluhue;
// Pencahue;
// Rauco;
// Retiro;
// Romeral;
// Río Claro;
// Sagrada Familia;
// San Clemente;
// San Javier;
// San Rafael;
// Talca;
// Teno;
// Vichuquén;
// Villa Alegre;
// Yerbas Buenas;
// Alto Biobío;
// Antuco;
// Arauco;
// Cabrero;
// Cañete;
// Chiguayante;
// Concepción;
// Contulmo;
// Coronel;
// Curanilahue;
// Florida;
// Hualqui;
// Laja;
// Lebu;
// Los Álamos;
// Los Ángeles;
// Lota;
// Mulchén;
// Nacimiento;
// Negrete;
// Penco;
// Quilaco;
// Quilleco;
// San Pedro de la Paz;
// San Rosendo;
// Santa Bárbara;
// Santa Juana;
// Talcahuano;
// Tirúa;
// Tomé;
// Tucapel;
// Yumbel;
// Alto del Carmen;
// Angol;
// Carahue;
// Cholchol;
// Collipulli;
// Cunco;
// Curacautín;
// Curarrehue;
// Ercilla;
// Freire;
// Galvarino;
// Gorbea;
// Lautaro;
// Loncoche;
// Lonquimay;
// Los Sauces;
// Lumaco;
// Melipeuco;
// Nueva Imperial;
// Padre Las Casas;
// Perquenco;
// Pitrufquén;
// Pucón;
// Purén;
// Renaico;
// Saavedra;
// Temuco;
// Teodoro Schmidt;
// Toltén;
// Traiguén;
// Victoria;
// Vilcún;
// Villarrica;
// Corral;
// Futrono;
// La Unión;
// Lago Ranco;
// Lanco;
// Los Lagos;
// Máfil;
// Mariquina;
// Paillaco;
// Panguipulli;
// Valdivia;
// Ancud;
// Calbuco;
// Castro;
// Chaitén;
// Chonchi;
// Cochamó;
// Curaco de Vélez;
// Dalcahue;
// Fresia;
// Frutillar;
// Futaleufú;
// Hualaihué;
// Llanquihue;
// Los Muermos;
// Maullín;
// Osorno;
// Palena;
// Puerto Montt;
// Puerto Octay;
// Puerto Varas;
// Puqueldón;
// Purranque;
// Puyehue;
// Queilén;
// Quellón;
// Quemchi;
// Quinchao;
// Puerto Aysén;
// Cisnes;
// Guaitecas;
// Cochrane;
// OHiggins;
// Tortel;
// Chile Chico;
// Río Ibáñez;
// Punta Arenas;
// Laguna Blanca;
// Río Verde;
// San Gregorio;
// Porvenir;
// Primavera;
// Timaukel;
// Natales;
// Torres del Paine;
// Antártica;
// Cabo de Hornos;
// Cerrillos;
// Cerro Navia;
// Conchalí;
// El Bosque;
// Estación Central;
// Huechuraba;
// Independencia;
// La Cisterna;
// La Florida;
// La Granja;
// La Pintana;
// La Reina;
// Las Condes;
// Lo Barnechea;
// Lo Espejo;
// Lo Prado;
// Macul;
// Maipú;
// Ñuñoa;
// Pedro Aguirre Cerda;
// Peñalolén;
// Providencia;
// Pudahuel;
// Quilicura;
// Quinta Normal;
// Recoleta;
// Renca;
// San Joaquín;
// San Miguel;
// San Ramón;
// Santiago;
// Vitacura;
// El Monte;
// Isla de Maipo;
// Padre Hurtado;
// Peñaflor;
// Talagante;

//       //Arica y Parinacota; Tarapacá; Antofagasta; Atacama; Coquimbo; Valparaíso; Metropolitana de Santiago; Libertador General Bernardo O\ Higgins; Maule; Biobío; La Araucanía; Los Ríos; Los Lagos; Aysén del General Carlos Ibáñez del Campo; Magallanes y de la Antártica Chilena;

    



